version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pinApp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    networks:
      - spring

  pin-app:
    container_name: pinApp
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: pinApp
      DB_USERNAME: root
      DB_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8:3306/pinApp?allowPublicKeyRetrieval=false&autoReconnect=true&useSSL=false
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

networks:
  spring:
    name: spring